# Generated by Django 5.1.2 on 2024-10-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cliente_dni_producto_precio_producto_texes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='texes',
            new_name='taxes',
        ),
    ]
