# Generated by Django 5.1.2 on 2024-10-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_rename_texes_producto_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
